server:
  port: 8089
spring:
  datasource:
    url: jdbc:h2:mem:quiz
    driver-class-name: org.h2.Driver
    DB_CLOSE_ON_EXIT: FALSE
    username: sa
    password: sa
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8 
#  jpa:
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#  schema: classpath:db/schema.sql
#    data: classpath:db/data.sql
jpa:
    database: h2
    hibernate:
      ddl-auto: update
      show-sql: true
h2:
    console:
      path: /h2-console
      enabled: true
    settings:
      web-allow-others=true